nextcloud-libraries/nextcloud-l10n

- README.md
- babel.config.js
- lib/gettext.ts
- package-lock.json
- package.json
- test/gettext.test.js
- tsconfig.json
Working on https://github.com/nextcloud/nextcloud-vue/pull/854 I realized that node-gettext doesn't handle placeholders like we do in other translations. And there doesn't seem to be like a standard way for doing this. Thus I'm adding a little wrapper around node-gettext here, so we can have a unified translation system for npm packages (and possibly apps if we decide to get fancy and bundle translations).
So this adds
* The aforesaid module
* A builder to get a translation object (gettext offers more functions. but we don't use context nor domain, so I hid them)
* `{placeholder}` style replacement
* `%n` replacement for plurals
Open question(s)
> Add a wrapper around node-gettext with Nextcloud-style replacements

- lib/gettext.ts
- package-lock.json
- package.json
- test/gettext.test.js
Fixes https://github.com/nextcloud/nextcloud-l10n/issues/108
As of 3.0.0 the debug more is off by default. As it's still useful sometimes, I added it optionally via the builder.
Ref https://github.com/alexanderwallin/node-gettext/compare/v2.0.0...v3.0.0 for the full diff
I'll publish a minor release once this is in.
> Only log to console.warn when debug mode is active

- lib/gettext.ts
- package-lock.json
- package.json
Follow-up to #109. Now you can enable debug mode to see only warnings about the missing translations. The logs are actually helpful then :)
> Set the source locale to 'en'

- lib/gettext.ts
- Set Nextcloud language to `de_DE` or any other language that uses a `_` separator in the identifier. 
- Use `@nextcloud/vue` which comes with translations that are depending on the result of getLanguage `https://github.com/nextcloud/nextcloud-l10n/blob/master/lib/index.ts#L31`
`OC.getLanguage` just returns the lang value of the `<html>` element [however `-` are used there instead of `_`](https://github.com/nextcloud/server/blob/cbd20867b59779d7aff5a024e4287206e3c028e0/lib/private/TemplateLayout.php#L158) so the language cannot be found in the provided pot files of `@nextcloud/vue`:
Before:
- Strings don't get translated
After:
- String get properly translated
> Replace dash with underscore for applying proper languages

- lib/index.ts
This should prevent `No OC found` warnings.
`getLanguage` was the real issue, `getLocale` is only a bonus.
Server PR to prevent code duplication: https://github.com/nextcloud/server/pull/32257
Fix https://github.com/nextcloud/nextcloud-l10n/issues/433
> Remove OC dependency for getLocale and getLanguage

- .github/workflows/node.yml
- package-lock.json
- package.json
- test/index.test.js
Fixed jest tests - added missing jest environment
* For running jest tests a DOM environment has to be setup,
therefor happydom is now used.
* Fixed `getCanonicalLocale` tests as OC.getLocal is no
longer used but the root `data-locale` element.
Also added github workflow for running tests
> Fix tests and add github workflow to ensure they succeed

- README.md
Old badge used travis, which was removed some time ago, use github workflow status instead.
> Fix "build status" badge in README.mde

- .github/workflows/documentation.yml
- lib/gettext.ts
- lib/index.ts
- lib/translation.ts
- package-lock.json
- package.json
- typedoc.json
The current `build:doc` script does not work, as `typedoc` has changed its interface, this is fixed by the first commit.
Also the documentation is not deployed anymore since travis was removed, this is fixed by the second commit which uses a github action for documentation deployment.
> Fix building and deploying documentaton

- tests/gettext.test.js
This provides missing test cases for 100% code coverage of `gettext.ts`.
* Fallback to `en` if not locale is set
* If placeholder value is not a string or number output the placeholder itself
> Add missing test cases for `gettext.ts`

- package-lock.json
- package.json
- tests/date.test.ts
- tests/index.test.js
This adds the missing test cases for `date.ts` to increase code coverage of it to 100%.
Mainly this adds tests for `@nextcloud/l10n` to use `window.????`  if provided and also tests for emitting warnings on the console if the defaults are used.
This also adds support for tests written in TypeScript (adds the missing typings).
> Add missing test cases for `date.ts`

- .eslintrc.json
- .github/workflows/lint-eslint.yml
- jest.config.js
- lib/date.ts
- lib/gettext.ts
- lib/index.ts
- lib/registry.ts
- lib/translation.ts
- package-lock.json
- package.json
- rollup.config.mjs
- tests/date.test.ts
- tests/gettext.test.js
- tests/index.test.js
Now that our eslint config supports TypeScript we would make use of it, what do you think?
I pushed the fixes for problems found as different commits to make reviewing the changes easier (you could review a single commit a time and compare with the description from the commit message), as the changes are quite huge.
> Enforce nextcloud code style | Adding eslint linting

- .npmignore
Fix #560 
```bash
$ npm pack 
npm notice 
npm notice 📦  @nextcloud/l10n@2.0.0
npm notice === Tarball Contents ===
npm notice 1.9kB  CHANGELOG.md
npm notice 35.1kB LICENSE
npm notice 2.3kB  README.md
npm notice 748B   dist/date.d.ts
npm notice 1.4kB  dist/gettext.d.ts
npm notice 3.0kB  dist/gettext.js
npm notice 3.0kB  dist/gettext.mjs
npm notice 428B   dist/index.d.ts
npm notice 16.0kB dist/index.js
npm notice 15.7kB dist/index.mjs
npm notice 1.2kB  dist/registry.d.ts
npm notice 2.7kB  dist/translation.d.ts
npm notice 1.8kB  package.json
npm notice === Tarball Details === 
```
> fix(config): fix npmignore config

- rollup.config.mjs
- tsconfig.json
Fix #561 
We need to use the tsconfig, or else it's no use at all.
Removing the overriden declaration in rollup make the rollup plugin fetch the tsconfig.json file 
```bash
$ npm run build 
$ tree dist
dist
├── date.d.ts
├── gettext.d.ts
├── gettext.js
├── gettext.mjs
├── index.d.ts
├── index.js
├── index.mjs
├── registry.d.ts
└── translation.d.ts
0 directories, 9 files
```
> fix(config): fix tsconfig out dir typings

- lib/registry.ts
- tests/index.test.js
In 2.0.0 `@nextcluod/l10n` became independent from global `OC` for being standalone.
That is great and really useful for me.
But a translation registration requires global `window._oc_l10n_registry_*` objects to exist. Otherwise, registration fails with `Cannot get property of undefined`.
- Added checking of `_oc_l10n_registry_` objects existence and creating if they do not exist.
- Added tests for translation registration
> Fix standalone registeration

- lib/registry.ts
- lib/translation.ts
- package.json
- tests/registry.test.ts
Found some time today for adding more tests for `registry.ts` to achieve 100% code coverage.
While doing so, by the help of those tests, I noticed types for `Translations` were not correct (plural form of strings).
So this PR includes fixes for the types, as well as some code changes which result from changing the types.
I decided to not squash the commits so might get some context why I changed something the way I did.
| before | after |
|-----------|--------|
| ![code coverage before, 95.65% statements, 85.71% branches](https://user-images.githubusercontent.com/1855448/213487728-41bde906-fbe0-46de-8a0a-daf4a3733fa5.png) |![code coverage after, 100% statements, 100% branches](https://user-images.githubusercontent.com/1855448/213487472-9e77333b-163c-42f0-8bd3-3ee6fa55d5e7.png) |
> Add more tests for `registry.ts` and fix typings

- lib/index.ts
- lib/registry.ts
Add some missing documentation comments and export the `Translations` type as that is used by public API the type should be exported as well.
> Add missing documentation

- lib/translation.ts
Our implementation of `getLanguage()` does have a fallback to English, so it does never return `undefined` or an empty string.
This conditional was from the server implementation where `getLanguage` might returned a falsy value.
> fix: Remove dead code from previous server implementation

- lib/registry.ts
- tests/gettext.test.js
- tests/registry.test.ts
In 1.x translations registry was initialized in `OC.L10N`. The initialization includes defining global variables on script load: <https://github.com/nextcloud/server/blob/352bd7ecea488201e4162e4e31a0cf9770cf20a0/core/src/OC/l10n-registry.js#L24-L26>
```js
// server/core/src/OC/l10n-registry.js 
window._oc_l10n_registry_translations = window._oc_l10n_registry_translations || {}
window._oc_l10n_registry_plural_functions = window._oc_l10n_registry_plural_functions || {}
```
After an update `@nextcloud/l10n@2.0.0`, the lib becomes independent from the server's `OC.L10N`. But it still required `window._oc_l10n_registry_translations` to be initialized and warned `No OC L10N registry found`.
In https://github.com/nextcloud/nextcloud-l10n/pull/556 it was fixed by defining …
> Remove warning "No translation for appId "${appId}" have been registered"

- tests/translation.test.ts
I think testing each branch within `getPlural` is hard as it requires adding the same logic to the tests, but at least we should test for some special branches for exceptions.
> feat(tests): Add some basic tests for `getPlural`

- lib/translation.ts
- package-lock.json
- package.json
- tests/loadTranslations.test.ts
There is a small issue which completely changed the behavior of `loadTranslation` to be synchronous while it should be (and is in `OC.L10N`) asynchronous. This is fixed, also added more information if the request fails.
Added test cases for `loadTranslation`
| before | after |
|---|----|
| ![code coverage 60.91% statements 13.5% branches](https://user-images.githubusercontent.com/1855448/214821148-c203989a-6cf3-4efa-8462-b47c2be88fe7.png) | ![code coverage 80.89% statements 18.85% branches](https://user-images.githubusercontent.com/1855448/214821698-d9ae6836-c966-4707-8f5c-22e5b5ed9697.png) |
> Fix loading translations and add test cases

- lib/translation.ts
- tests/loadTranslations.test.ts
- tests/translation.test.ts
* Resolves #574 
Lets promote the register function to the public API.
> feat: Promote `unregister` function to public API

- CHANGELOG.md
- package-lock.json
- package.json
- `unregister` is now part of the public API [\#579](https://github.com/nextcloud/nextcloud-l10n/pull/579) ([susnux](https://github.com/susnux))
- Export the `Translations` type and add missing documentation [\#566](https://github.com/nextcloud/nextcloud-l10n/pull/566) ([susnux](https://github.com/susnux))
- Fix singular translation in edge cases where plural strings are provided [\#570](https://github.com/nextcloud/nextcloud-l10n/pull/570) ([susnux](https://github.com/susnux))
- Make loading translations use async XMLHttpRequest [\#571](https://github.com/nextcloud/nextcloud-l10n/pull/571) ([susnux](https://github.com/susnux))
- Removed warning "no app translation was registered" [\#572](https://github.com/nextcloud/nextcloud-l10n/pull/572) ([ShGKme](https://github.com/ShGKme))
- Added …
> Prepare 2.1.0 release

- package-lock.json
- package.json
This ensures that dependents of `@nextcloud/l10n` get the typings.
This follows the suggestions of https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies.
Fixes https://github.com/nextcloud/nextcloud-l10n/issues/609
> fix(deps): Make @nextcloud/typings a regular dependency

- package.json
This is required to make the package work with typescript projects which set the module resolution to `node16` or `nodenext` (only the `exports` field is evaluated but not the `types` field).
> fix: Add the typings to the package exports

- lib/date.ts
- lib/registry.ts
Updates the exported window typing to the latest Nextcloud typings (Nextcloud 27).
(Side note: We should maybe provide a `Nextcloud.latest.`  namespace on the typings package).
> fix: Update exported `NextcloudWindowWithRegistry` type

- lib/index.ts
- lib/locale.ts
- lib/translation.ts
- tests/locale.test.ts
- tests/translation.test.ts
* Resolves: #84 
Add `isRTL` to check whether a given, or the current, language is right-to-left read.
Use cases would be e.g. https://github.com/nextcloud/server/issues/31420 or https://github.com/nextcloud/forms/issues/1637 
:test_tube:  Testcases included
> feat: Add new `isRTL` function

- .github/workflows/node-test.yml
- package.json
coverage: https://app.codecov.io/github/nextcloud/nextcloud-l10n/pull/642
template: https://github.com/nextcloud/.github/pull/185
> feat: add node testing workflow

- .npmignore
- CHANGELOG.md
- package-lock.json
- package.json
If accepted, could someone of you with admin permission create the GH release so the NPM release workflow works?
---
- `isRTL` was added to check whether a given, or the current, language is read right-to-left [\#639](https://github.com/nextcloud/nextcloud-l10n/pull/639) ([susnux](https://github.com/susnux))
- Add typings to the package exports to fix build for Typescript projects using `node16` or `nodenext` module resolution [\#633](https://github.com/nextcloud/nextcloud-l10n/pull/633) ([susnux](https://github.com/susnux))
- Update exported `NextcloudWindowWithRegistry` type for Nextcloud 27 [\#640](https://github.com/nextcloud/nextcloud-l10n/pull/640) ([susnux](https://github.com/susnux))
- Update node engines to next LTS (Node 20 + NPM 9)
- Dependency updates
> Prepare new release: v2.2.0

- lib/translation.ts
- tests/loadTranslations.test.ts
Should not happen, but lets be defensive and handle even the cases where the server might return invalid data.
(thanks @ code coverage that notified there is a missing test for this branch).
> fix(loadTranslations): Handle edge cases

- CHANGELOG.md
@skjnldsv in this case, lets include all merges in the next release as the release process was stopped in time.
> chore: Adjust changelog for 2.2.0 release

- lib/translation.ts
- tests/translation.test.ts
Not sure if this is a bug fix or a new feature but:
There is no need to sanitize the replacement values as it is sufficient to sanitize the result.
1. This will improve the performance if multiple placeholders are used.
2. This allows this: `See {linkstart}documentation{linkend}` with `{ linkstart: '<a ...>', linkend: '</a>' }` while the string is still sanitized.
> fix!: Only sanitize the result string when replacing variables

- CHANGELOG.md
- package-lock.json
- package.json
Instead of also sanitizing the replacing variables, now only the result is sanitized, see [pull request #648](https://github.com/nextcloud-libraries/nextcloud-l10n/pull/648).
This will improve the performance if multiple placeholders are used and it allows this, 
while the string is still sanitized:
```js
t(
`See {linkstart}documentation{linkend}`,
{
linkstart: '<a ...>',
linkend: '</a>',
},
// No number
undefined,
{
// Do not escape the result as we want the HTML anchor element
escape: false,
}
)
```
* feat: export aliases `t` and `n` for `translate` and `translatePlural`
* fix!: Only sanitize the result string when replacing variables
* Update NPM to latest LTS v10
* Migrate to vite for transpiling and vitest for testing
* chore: Added more tests for special cases on plural forms
* …
> chore: Prepare 3.0.0 release

- CHANGELOG.md
- package-lock.json
- package.json
*   Allow setting `escape` option per parameter replacing.\
For more security this should be used instead of disabling paramter escaping,
see [pull request #756](https://github.com/nextcloud-libraries/nextcloud-l10n/pull/756)
```js
// Example
t(
'my-app',
'{a}{userInput}{a_end}',
{
a: {
value: '<a>',
escape: false,
},
userInput: somePossiblyInsecureValue, // This will be escaped
a_end: {
value: '</a>',
escape: false,
}
},
)
```
> chore: Prepare 3.1.0 release

- lib/translation.ts
```ts
// ✅ Ok
t('app', 'Hello, {name}!', { name: 'Alice' })
// ✅ Ok
t('app', 'Hello, {name}!', { user: 'Alice' })
// ✅ Ok
t('app', 'Hello, {name}!', {})
```
```ts
// ✅ Ok
t('app', 'Hello, {name}!', { name: 'Alice' })
// ❌ Object literal may only specify known properties, and 'user' does not exist in type 'TranslationVariables<"Hello, {name}!">'
t('app', 'Hello, {name}!', { user: 'Alice' })
// ❌ Argument of type '{}' is not assignable to parameter of type 'TranslationVariables<"Hello, {name}!">'.
//  Property 'name' is missing in type '{}' but required in type 'TranslationVariables<"Hello, {name}!">'
t('app', 'Hello, {name}!', {})
```
> fix(types): type translation variable keys

- lib/date.ts
- tests/date.test.ts
Currently all the function from `date` module returns required server rendered global variables like
```js
window.dayNames
```
This PR allows to use these functions outside the server render context (apps) using `Intl`, for example:
- Web-Browser workers
- Documentations
- Talk Desktop
Drawbacks:
- `firstDay` is not available on Firefox
- Intl weekday in narrow format is different from `dayNamesMin`
1. Add an init method to set these variables with the same Intl values
2. Do nothing, this is not a real problem
> feat(date): fallback to Intl

- lib/date.ts
- lib/gettext.ts
- lib/index.ts
- lib/locale.ts
- lib/registry.ts
- lib/translation.ts
- package-lock.json
- package.json
- typedoc.json
* Resolves https://github.com/nextcloud-libraries/nextcloud-l10n/issues/836
> doc: replace missing exports plugin to also document internal types

- CHANGELOG.md
- lib/gettext.ts
The name was misleading and inconsistent with our `setLanguage` method.
> feat(gettext): Add `detectLanguage` method and deprecate `detectLocale`

- lib/locale.ts
- tests/locale.test.ts
* Resolves #803 
Summary:
- Nextcloud uses the BCP47 code `ur-PK` for Urdu
- Use language and not locale for `Uzbek Afghan` as we do for all others
> fix(isRTL): Correctly handle Urdu and Uzbek Afghan

- lib/translation.ts
- tests/translation.test.ts
It makes no sense for the singular translate method to allow both at the same time. It causes developers to add a `undefined` just to be able to pass option. So allow one of both as the third parameter and deprecate the 5-parameters overload so we can remove it in v4.
Before:
```js
translate('app', 'Number: %n', undefined, 4)
translate('app', 'Hello {name}', { name: 'John' })
translate('app', 'See our {linkStart}documentation{linkEnd}.', { ... }, undefined, { escape: false })
```
After:
```js
translate('app', 'Number: %n', 4)
translate('app', 'Hello {name}', { name: 'John' })
translate('app', 'See our {linkStart}documentation{linkEnd}.', { ... }, { escape: false })
```
> feat: Overload translate function to either allow number or placeholder as third arg

- .eslintrc.json
- lib/gettext.ts
- lib/registry.ts
- lib/translation.ts
- package-lock.json
- package.json
- tests/gettext.test.ts
- tests/translation.test.ts
- tsconfig.json
* Resolves https://github.com/nextcloud-libraries/nextcloud-l10n/issues/845
Instead of relying on a (insecure!) dependency we can reuse our already implemented logic for translations.
So we reuse the app translation logic also for the gettext based translations.
1. Allow to pass the translation bundle to our translation functions
2. Convert gettext JSON format to our Nextcloud translation format in the GettextBuilder.
3. Wrap the translation function within out gettext wrapper class
For the enduser this should not change anything (except that we do not have the debug messages `node-gettext` provided).
> refactor(gettext): Drop `node-gettext` dependency and use our translation logic

- .eslintrc.json
- lib/date.ts
Nice to have after https://github.com/nextcloud/server/pull/46592
> docs: improve return type of getFirstDay()

- lib/registry.ts
Potential fix for [https://github.com/nextcloud-libraries/nextcloud-l10n/security/code-scanning/1](https://github.com/nextcloud-libraries/nextcloud-l10n/security/code-scanning/1)
To fix the problem, we need to ensure that the `appId` cannot be used to modify the `Object.prototype`. This can be achieved by validating the `appId` before using it as a key in the object assignment. We will reject any `appId` that matches `__proto__`, `constructor`, or `prototype`.
> fix(registry): Prevent prototype polluting

- CHANGELOG.md
- package-lock.json
- package.json
The `GettextBuilder.detectLocale` method is deprecated and will be removed in the next major version.
It is replaced with the `detectLanguage` method to make the method naming more consistent.
* feat(date): fallback to Intl [\#831](https://github.com/nextcloud-libraries/nextcloud-l10n/pull/831) \([ShGKme](https://github.com/ShGKme)\)
* feat(gettext): Add `detectLanguage` method and deprecate `detectLocale` [\#850](https://github.com/nextcloud-libraries/nextcloud-l10n/pull/850) \([susnux](https://github.com/susnux)\)
* feat: Overload translate function to either allow number or placeholder as third arg [\#854](https://github.com/nextcloud-libraries/nextcloud-l10n/pull/854) \([susnux](https://github.com/susnux)\)
* fix(types): type translation variable keys …
> chore: Prepare v3.2.0

- lib/index.ts
- lib/time.ts
- tests/time.test.ts
* needed for https://github.com/nextcloud/server/issues/29807
* replaces https://github.com/nextcloud-libraries/nextcloud-vue/pull/6543
Lets have localization related methods together here at this place.
> feat: add method to format relative time

- CHANGELOG.md
- lib/translation.ts
- package-lock.json
- package.json
- tests/loadTranslations.test.ts
- Use language instead of locale for loading translations.
- Refactor to use `fetch` API instead of `XMLHttpRequest`.
- Deprecate `callback` parameter in favor of directly using the returned promise.
- Use MSW for tests.
> fix(translations): use language instead of locale + refactor the `loadTranslations` method

- lib/locale.ts
- package.json
- tests/locale.test.ts
When language or locale is not available, `@nextcloud/l10n` fallbacks to `'en'`.
Instead, fallback to the environment (aka Web-Brrowser/OS) settings.
Alternative: fallback locale to language instead of system locale.
> fix(locale): fallback to device preferences instead of 'en'

- lib/date.ts
- lib/globals.d.ts
- lib/locale.ts
- lib/registry.ts
- lib/translation.ts
- package.json
- tests/date.test.ts
- tests/gettext.test.ts
- tests/is-rtl.test.ts
- tests/loadTranslations.test.ts
- tests/locale.test.ts
- tests/registry.test.ts
- tests/time.test.ts
- tests/translation.test.ts
- tests/tsconfig.json
- vite.config.ts
- Resolves #830
- Based on #832
Allows to use the library in web workers and similar other places.
- Adjusted `window` and `document` usage (`globalThis`)
- Add global state handling as there is no document
- Added tests for also non-DOM environment
Limitations in non DOM environments:
- Sanitizing of HTML does not work as DOMPurify needs a DOM
- `loadTranslations` needs `@nextcloud/router` to work
> feat: add support for universal environment

- lib/gettext.ts
- tests/gettext.test.ts
This allows us to only register what is needed.
Normally you would register everything at once,
but for performance reasons the `nextcloud-vue`
library only registers the translations of components that are really used.
> feat(gettext): allow to add translations to the wrapper
